/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation List */
        get: operations["get_conversation_list_api_v1_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation Detail */
        get: operations["get_conversation_detail_api_v1_conversations__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Backup */
        post: operations["create_backup_api_v1_data_backups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly Reviews */
        get: operations["weekly_reviews_api_v1_insights_weekly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/learning/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Learning */
        get: operations["search_learning_api_v1_learning_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Log Cancellation */
        post: operations["post_log_cancellation_api_v1_logs_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Log Confirmation */
        post: operations["post_log_confirmation_api_v1_logs_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logs */
        get: operations["get_logs_api_v1_logs__domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs/{domain}/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Log */
        delete: operations["delete_log_api_v1_logs__domain___record_id__delete"];
        options?: never;
        head?: never;
        /** Patch Log */
        patch: operations["patch_log_api_v1_logs__domain___record_id__patch"];
        trace?: never;
    };
    "/api/v1/media/extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Image Extraction */
        post: operations["post_image_extraction_api_v1_media_extractions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Transcription */
        post: operations["post_transcription_api_v1_media_transcriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Message */
        post: operations["post_message_api_v1_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Message Stream */
        post: operations["post_message_stream_api_v1_messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_v1_settings_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerDateRange */
        AnswerDateRange: {
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
        };
        /** ApiResponse[BackupData] */
        ApiResponse_BackupData_: {
            data?: components["schemas"]["BackupData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[CancelLogData] */
        ApiResponse_CancelLogData_: {
            data?: components["schemas"]["CancelLogData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[ConfirmLogData] */
        ApiResponse_ConfirmLogData_: {
            data?: components["schemas"]["ConfirmLogData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[ConversationDetailData] */
        ApiResponse_ConversationDetailData_: {
            data?: components["schemas"]["ConversationDetailData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[ConversationListData] */
        ApiResponse_ConversationListData_: {
            data?: components["schemas"]["ConversationListData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[DashboardSummary] */
        ApiResponse_DashboardSummary_: {
            data?: components["schemas"]["DashboardSummary"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[HealthData] */
        ApiResponse_HealthData_: {
            data?: components["schemas"]["HealthData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[ImageExtractionData] */
        ApiResponse_ImageExtractionData_: {
            data?: components["schemas"]["ImageExtractionData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[LearningSearchResult] */
        ApiResponse_LearningSearchResult_: {
            data?: components["schemas"]["LearningSearchResult"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[MessageData] */
        ApiResponse_MessageData_: {
            data?: components["schemas"]["MessageData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[RecordDeletionData] */
        ApiResponse_RecordDeletionData_: {
            data?: components["schemas"]["RecordDeletionData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[RecordMutationData] */
        ApiResponse_RecordMutationData_: {
            data?: components["schemas"]["RecordMutationData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[RecordPage] */
        ApiResponse_RecordPage_: {
            data?: components["schemas"]["RecordPage"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[SettingsData] */
        ApiResponse_SettingsData_: {
            data?: components["schemas"]["SettingsData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[TranscriptionData] */
        ApiResponse_TranscriptionData_: {
            data?: components["schemas"]["TranscriptionData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** ApiResponse[WeeklyReviewsData] */
        ApiResponse_WeeklyReviewsData_: {
            data?: components["schemas"]["WeeklyReviewsData"] | null;
            error?: components["schemas"]["ApiError"] | null;
            /** Request Id */
            request_id: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** AppPreferences */
        AppPreferences: {
            /** Default Currency */
            default_currency: string;
            /** Sleep Hours Target */
            sleep_hours_target: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weekly Learning Minutes */
            weekly_learning_minutes: number;
            /** Weekly Spending Limit */
            weekly_spending_limit?: number | null;
            /** Weekly Workouts */
            weekly_workouts: number;
        };
        /** AppPreferencesPatch */
        AppPreferencesPatch: {
            /** Default Currency */
            default_currency?: string | null;
            /** Sleep Hours Target */
            sleep_hours_target?: number | null;
            /** Weekly Learning Minutes */
            weekly_learning_minutes?: number | null;
            /** Weekly Spending Limit */
            weekly_spending_limit?: number | null;
            /** Weekly Workouts */
            weekly_workouts?: number | null;
        };
        /** BackupData */
        BackupData: {
            /** Backup Name */
            backup_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Includes */
            includes: string[];
            /** Warnings */
            warnings?: string[];
        };
        /** Body_post_image_extraction_api_v1_media_extractions_post */
        Body_post_image_extraction_api_v1_media_extractions_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_post_transcription_api_v1_media_transcriptions_post */
        Body_post_transcription_api_v1_media_transcriptions_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CancelLogData */
        CancelLogData: {
            /**
             * Assistant Text
             * @default Draft cancelled. Nothing was saved.
             */
            assistant_text: string;
            /**
             * Response Type
             * @default cancellation
             * @constant
             */
            response_type: "cancellation";
            /** Thread Id */
            thread_id: string;
        };
        /** CancelLogRequest */
        CancelLogRequest: {
            /** Thread Id */
            thread_id: string;
        };
        /** CategorySummary */
        CategorySummary: {
            /** Category */
            category: string;
            /** Currency */
            currency: string;
            /** Records */
            records: number;
            /** Total */
            total: number;
        };
        /** ConfirmLogData */
        ConfirmLogData: {
            /** Assistant Text */
            assistant_text: string;
            daily_status: components["schemas"]["DailyStatusData"];
            /** Entities */
            entities?: {
                [key: string]: unknown;
            }[];
            record_ids: components["schemas"]["SavedRecordIds"];
            /**
             * Response Type
             * @default confirmation
             * @constant
             */
            response_type: "confirmation";
            saved: components["schemas"]["SavedRecordCounts"];
            /** Thread Id */
            thread_id: string;
            /** Warnings */
            warnings?: string[];
        };
        /** ConfirmLogRequest */
        ConfirmLogRequest: {
            draft: components["schemas"]["DailyLogDraft"];
            /** Thread Id */
            thread_id: string;
        };
        /** ConversationDetailData */
        ConversationDetailData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Messages */
            messages?: components["schemas"]["ConversationMessageData"][];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConversationListData */
        ConversationListData: {
            /** Items */
            items?: components["schemas"]["ConversationSummaryData"][];
        };
        /** ConversationMessageData */
        ConversationMessageData: {
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** ConversationSummaryData */
        ConversationSummaryData: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Last Message */
            last_message?: string | null;
            /** Message Count */
            message_count: number;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CurrencyNet */
        CurrencyNet: {
            /** Currency */
            currency: string;
            /** Expense */
            expense: number;
            /** Income */
            income: number;
            /** Net */
            net: number;
        };
        /** CurrencySummary */
        CurrencySummary: {
            /** Currency */
            currency: string;
            /** Records */
            records: number;
            /** Total */
            total: number;
        };
        /** DailyHealthPoint */
        DailyHealthPoint: {
            /** Calories Consumed */
            calories_consumed?: number | null;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Sleep Hours */
            sleep_hours?: number | null;
            /** Workout Type */
            workout_type?: string | null;
        };
        /** DailyLearningPoint */
        DailyLearningPoint: {
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Minutes */
            minutes: number;
            /** Sessions */
            sessions: number;
        };
        /** DailyLogDraft */
        DailyLogDraft: {
            /** Ambiguities */
            ambiguities?: string[];
            /**
             * Confidence
             * @default 0.8
             */
            confidence: number;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            health?: components["schemas"]["HealthLog"] | null;
            /** Learning */
            learning?: components["schemas"]["LearningLog"][];
            /**
             * Operation
             * @default create
             * @enum {string}
             */
            operation: "create" | "update";
            /** Original Input */
            original_input: string;
            /**
             * Source
             * @default text
             * @enum {string}
             */
            source: "text" | "voice" | "image" | "mixed";
            /** Target Domain */
            target_domain?: ("wealth" | "health" | "learning") | null;
            /** Target Record Id */
            target_record_id?: number | null;
            /** Wealth */
            wealth?: components["schemas"]["WealthLog"][];
        };
        /** DailyStatusData */
        DailyStatusData: {
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Health Complete */
            health_complete: boolean;
            /** Is Complete */
            is_complete: boolean;
            /** Learning Complete */
            learning_complete: boolean;
            /** Wealth Reviewed */
            wealth_reviewed: boolean;
        };
        /** DailyWealthPoint */
        DailyWealthPoint: {
            /** Currency */
            currency: string;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Expense */
            expense: number;
            /** Income */
            income: number;
            /** Net */
            net: number;
        };
        /** DashboardDateRange */
        DashboardDateRange: {
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** DashboardSummary */
        DashboardSummary: {
            daily_status: components["schemas"]["DailyStatusData"];
            date_range: components["schemas"]["DashboardDateRange"];
            health: components["schemas"]["HealthDashboard"];
            learning: components["schemas"]["LearningDashboard"];
            /**
             * Status Date
             * Format: date
             */
            status_date: string;
            wealth: components["schemas"]["WealthDashboard"];
        };
        /** DependencyHealth */
        DependencyHealth: {
            /** Detail */
            detail?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthDashboard */
        HealthDashboard: {
            /** Average Calories */
            average_calories?: number | null;
            /** Average Sleep Hours */
            average_sleep_hours?: number | null;
            /** Calorie Records */
            calorie_records: number;
            /** Daily */
            daily: components["schemas"]["DailyHealthPoint"][];
            /** Sleep Records */
            sleep_records: number;
            /** Workout Days */
            workout_days: number;
        };
        /** HealthData */
        HealthData: {
            database: components["schemas"]["DependencyHealth"];
            /** Environment */
            environment: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            vector_store: components["schemas"]["DependencyHealth"];
        };
        /** HealthLog */
        HealthLog: {
            /** Calories Consumed */
            calories_consumed?: number | null;
            /** Notes */
            notes?: string | null;
            /** Sleep Hours */
            sleep_hours?: number | null;
            /** Workout Type */
            workout_type?: string | null;
        };
        /** HealthRecord */
        HealthRecord: {
            /** Calories Consumed */
            calories_consumed?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Id */
            id: number;
            /** Notes */
            notes?: string | null;
            /** Sleep Hours */
            sleep_hours?: number | null;
            /** Source */
            source: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workout Type */
            workout_type?: string | null;
        };
        /** ImageExtractionData */
        ImageExtractionData: {
            /** Content Type */
            content_type: string;
            /** Height */
            height: number;
            /**
             * Media Type
             * @default image
             * @constant
             */
            media_type: "image";
            /** Text */
            text: string;
            /** Width */
            width: number;
        };
        /** LearningDashboard */
        LearningDashboard: {
            /** Current Streak Days */
            current_streak_days: number;
            /** Daily */
            daily: components["schemas"]["DailyLearningPoint"][];
            /** Learning Days */
            learning_days: number;
            /** Longest Streak Days */
            longest_streak_days: number;
            /** Sessions */
            sessions: number;
            /** Topics */
            topics: components["schemas"]["TopicSummary"][];
            /** Total Minutes */
            total_minutes: number;
        };
        /** LearningLog */
        LearningLog: {
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Summary Text */
            summary_text: string;
            /** Topic */
            topic: string;
            /** Url Reference */
            url_reference?: string | null;
        };
        /** LearningRecord */
        LearningRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Summary Text */
            summary_text?: string | null;
            /** Topic */
            topic: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url Reference */
            url_reference?: string | null;
        };
        /** LearningSearchHit */
        LearningSearchHit: {
            /** Distance */
            distance?: number | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Record Id */
            record_id: number;
            /** Summary Text */
            summary_text: string;
            /** Topic */
            topic: string;
            /** Url Reference */
            url_reference?: string | null;
        };
        /** LearningSearchRequest */
        LearningSearchRequest: {
            /** End Date */
            end_date?: string | null;
            /**
             * Limit
             * @default 3
             */
            limit: number;
            /** Query Text */
            query_text: string;
            /** Start Date */
            start_date?: string | null;
            /** Topic */
            topic?: string | null;
        };
        /** LearningSearchResult */
        LearningSearchResult: {
            /** Hits */
            hits?: components["schemas"]["LearningSearchHit"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "vector" | "sqlite_fallback" | "empty";
            request: components["schemas"]["LearningSearchRequest"];
            /** Warning */
            warning?: string | null;
        };
        /** MessageData */
        MessageData: {
            /** Assistant Text */
            assistant_text: string;
            /** Confidence */
            confidence?: number | null;
            date_range?: components["schemas"]["AnswerDateRange"] | null;
            draft?: components["schemas"]["DailyLogDraft"] | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
            /**
             * Response Type
             * @enum {string}
             */
            response_type: "log_draft" | "query_answer" | "clarification" | "message" | "error";
            /** Thread Id */
            thread_id: string;
        };
        /** MessageRequest */
        MessageRequest: {
            /** Entry Date */
            entry_date?: string | null;
            /** Message */
            message: string;
            /**
             * Source
             * @default text
             * @enum {string}
             */
            source: "text" | "voice" | "image" | "mixed";
            /** Thread Id */
            thread_id?: string | null;
        };
        /** ProviderConfiguration */
        ProviderConfiguration: {
            /** Capability */
            capability: string;
            /** Configured */
            configured: boolean;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
        };
        /** RecordDeletionData */
        RecordDeletionData: {
            /** Deleted Id */
            deleted_id: number;
            domain: components["schemas"]["RecordDomain"];
            status: components["schemas"]["DailyStatusData"];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * RecordDomain
         * @enum {string}
         */
        RecordDomain: "wealth" | "health" | "learning";
        /** RecordMutationData */
        RecordMutationData: {
            domain: components["schemas"]["RecordDomain"];
            /** Record */
            record: components["schemas"]["WealthRecord"] | components["schemas"]["HealthRecord"] | components["schemas"]["LearningRecord"];
            /** Statuses */
            statuses: {
                [key: string]: components["schemas"]["DailyStatusData"];
            };
            /** Warnings */
            warnings?: string[];
        };
        /** RecordPage */
        RecordPage: {
            domain: components["schemas"]["RecordDomain"];
            /** Items */
            items: (components["schemas"]["WealthRecord"] | components["schemas"]["HealthRecord"] | components["schemas"]["LearningRecord"])[];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /** RecordPatch */
        RecordPatch: {
            /** Amount */
            amount?: number | null;
            /** Calories Consumed */
            calories_consumed?: number | null;
            /** Category */
            category?: string | null;
            /** Currency */
            currency?: string | null;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Entry Date */
            entry_date?: string | null;
            /** Merchant */
            merchant?: string | null;
            /** Notes */
            notes?: string | null;
            /** Sleep Hours */
            sleep_hours?: number | null;
            /** Summary Text */
            summary_text?: string | null;
            /** Topic */
            topic?: string | null;
            /** Transaction Type */
            transaction_type?: ("Income" | "Expense") | null;
            /** Url Reference */
            url_reference?: string | null;
            /** Workout Type */
            workout_type?: string | null;
        };
        /** SavedRecordCounts */
        SavedRecordCounts: {
            /** Health */
            health: number;
            /** Learning */
            learning: number;
            /** Wealth */
            wealth: number;
        };
        /** SavedRecordIds */
        SavedRecordIds: {
            /** Health */
            health?: number[];
            /** Learning */
            learning?: number[];
            /** Wealth */
            wealth?: number[];
        };
        /** SettingsData */
        SettingsData: {
            preferences: components["schemas"]["AppPreferences"];
            /** Providers */
            providers: components["schemas"]["ProviderConfiguration"][];
        };
        /** TopicSummary */
        TopicSummary: {
            /** Minutes */
            minutes: number;
            /** Sessions */
            sessions: number;
            /** Topic */
            topic: string;
        };
        /** TranscriptionData */
        TranscriptionData: {
            /** Content Type */
            content_type: string;
            /** Duration Seconds */
            duration_seconds: number;
            /**
             * Media Type
             * @default audio
             * @constant
             */
            media_type: "audio";
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WealthDashboard */
        WealthDashboard: {
            /** Categories */
            categories: components["schemas"]["CategorySummary"][];
            /** Daily */
            daily: components["schemas"]["DailyWealthPoint"][];
            /** Expenses */
            expenses: components["schemas"]["CurrencySummary"][];
            /** Income */
            income: components["schemas"]["CurrencySummary"][];
            /** Net */
            net: components["schemas"]["CurrencyNet"][];
        };
        /** WealthLog */
        WealthLog: {
            /**
             * Amount
             * @description Amount spent or earned.
             */
            amount: number;
            /** Category */
            category: string;
            /**
             * Currency
             * @default INR
             */
            currency: string;
            /** Merchant */
            merchant?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Transaction Type
             * @enum {string}
             */
            transaction_type: "Income" | "Expense";
        };
        /** WealthRecord */
        WealthRecord: {
            /** Amount */
            amount: number;
            /** Category */
            category: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Id */
            id: number;
            /** Merchant */
            merchant?: string | null;
            /** Notes */
            notes?: string | null;
            /** Source */
            source: string;
            /**
             * Transaction Type
             * @enum {string}
             */
            transaction_type: "Income" | "Expense";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WeeklyReview */
        WeeklyReview: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
            /** Id */
            id: number;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /** WeeklyReviewsData */
        WeeklyReviewsData: {
            /**
             * Generation Available
             * @default false
             */
            generation_available: boolean;
            /** Message */
            message?: string | null;
            /** Reviews */
            reviews?: components["schemas"]["WeeklyReview"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_conversation_list_api_v1_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConversationListData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_detail_api_v1_conversations__thread_id__get: {
        parameters: {
            query?: {
                message_limit?: number;
            };
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConversationDetailData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                status_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_DashboardSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_backup_api_v1_data_backups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_BackupData_"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HealthData_"];
                };
            };
        };
    };
    weekly_reviews_api_v1_insights_weekly_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_WeeklyReviewsData_"];
                };
            };
        };
    };
    search_learning_api_v1_learning_search_get: {
        parameters: {
            query: {
                query: string;
                topic?: string | null;
                start_date?: string | null;
                end_date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_LearningSearchResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_log_cancellation_api_v1_logs_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelLogRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_CancelLogData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_log_confirmation_api_v1_logs_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmLogRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConfirmLogData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_api_v1_logs__domain__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                start_date?: string | null;
                end_date?: string | null;
                search?: string | null;
                source?: string | null;
                transaction_type?: ("Income" | "Expense") | null;
                currency?: string | null;
                category?: string | null;
                merchant?: string | null;
                workout_type?: string | null;
                topic?: string | null;
            };
            header?: never;
            path: {
                domain: components["schemas"]["RecordDomain"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RecordPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_log_api_v1_logs__domain___record_id__delete: {
        parameters: {
            query: {
                confirm: boolean;
            };
            header?: never;
            path: {
                domain: components["schemas"]["RecordDomain"];
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RecordDeletionData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_log_api_v1_logs__domain___record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["schemas"]["RecordDomain"];
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_RecordMutationData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_image_extraction_api_v1_media_extractions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_image_extraction_api_v1_media_extractions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ImageExtractionData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_transcription_api_v1_media_transcriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_transcription_api_v1_media_transcriptions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TranscriptionData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_api_v1_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MessageData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_stream_api_v1_messages_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events containing status, delta, and completion events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SettingsData_"];
                };
            };
        };
    };
    patch_settings_api_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppPreferencesPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_SettingsData_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
